plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'com.codeborne:selenide:7.7.3'
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'io.github.cdimascio:dotenv-java:3.0.0'
    implementation 'org.slf4j:slf4j-api:2.0.7'
    testImplementation 'ch.qos.logback:logback-classic:1.5.13'
}

test {
    useJUnitPlatform()
}